# 项目相关配置
bigo:
  # 名称
  name: Bycoin
  # 版本
  version: 2.3.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/bigo/uploadPath，Linux配置 /home/bigo/uploadPath）
  profile: @api.profile@
  # 获取ip地址开关
  addressEnabled: false
  # 文件上传前缀 -测试环境
  #fileUrl: http://192.168.0.8:8080
  # 文件上传前缀 -生产环境
  fileUrl: @api.address@

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8086
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.bigo: debug·
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: @redis.host@
    # 端口，默认为6379
    port: @redis.port@
    # 密码
    password: @redis.password@
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #Gmail邮箱配置
  mail:
    host: smtp.gmail.com
    username: @mail.username@
    password: @mail.password@
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: bigo2020
    # 令牌有效期（默认30分钟）
    expireTime: 14400
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.bigo.project.**.domain, com.bigo.project.**.vo, com.bigo.project.**.entity
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
# 代码生成
gen: 
  # 作者
  author: bigo
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.bigo.project.bigo.jackpot
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: bg_

# 傲众云短信平台信息
msg:
  appkey: kGWt1l0k
  secretkey: kGWt1l0k
    #发送短信地址
  sendUrl: http://api.wftqm.com/api/sms/mtsend
  #查询余额地址
  queryUrl: http://www.aozhongyun.com/Admin/index.php/Message/balance
  #发送注册短信模板
  regTemplate: Your verification code is {}, if you are not operating by yourself, please ignore this text message.
  sendName: @msg.sendName@


management:
  endpoint:
    shutdown:
      enabled: true  #启用shutdown
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /bigo # 自定义管理端点的前缀(保证安全)
  server:
    port: 8891
    address: 127.0.0.1 # 不允许远程管理连接(不允许外部调用保证安全)

config:
  trxService: @config.trxService@
  btcService: @config.btcService@
  btcPassword: @config.btcPassword@
  btcCollectionAddr: @config.btcCollectionAddr@
